"""mabowx 消息模型。"""

from .base import BaseMessage, HumanMessage, Message, NotExistsMessage
from .mtype import (
    CardMessage,
    EmotionMessage,
    FileMessage,
    ImageMessage,
    LinkMessage,
    LocationMessage,
    MergeMessage,
    MiniAppMessage,
    NoteMessage,
    OfficialMessage,
    OtherMessage,
    PersonalCardMessage,
    QuoteMessage,
    SystemMessage,
    TickleMessage,
    TextMessage,
    TimeMessage,
    VideoMessage,
    VoiceMessage,
)
from .mattr import FriendMessage, SelfMessage
from .msg import classify, make_message, parse_content

__all__ = [
    "CardMessage",
    "FriendMessage",
    "SelfMessage",
    "Message",
    "BaseMessage",
    "HumanMessage",
    "NotExistsMessage",
    "SystemMessage",
    "TickleMessage",
    "TimeMessage",
    "OfficialMessage",
    "TextMessage",
    "QuoteMessage",
    "VoiceMessage",
    "ImageMessage",
    "VideoMessage",
    "FileMessage",
    "LocationMessage",
    "LinkMessage",
    "EmotionMessage",
    "MergeMessage",
    "PersonalCardMessage",
    "NoteMessage",
    "MiniAppMessage",
    "OtherMessage",
    "classify",
    "make_message",
    "parse_content",
]
